### ISSUE TITLE
helper.zs error.

### ISSUE THREAD

**Issue by Oskal79** [Krutoy242/Craft.zs#1]
![image](https://user-images.githubusercontent.com/23283921/211545664-d8b8b1d7-d86b-4a73-8894-cf5ef106e02d.png)
https://pastebin.com/fhMeMFxk
What should i do for fix?

**Comment by Krutoy242** [comment]
Show me your helper.zs file, it's probably corrupted.
Also, what Craft Tweaker version do you use?

**Comment by Oskal79** [comment]
[helper.zip](https://github.com/Krutoy242/Craft.zs/files/10383674/helper.zip)

Version of CraftTweaker - [CraftTweaker-forge-1.18.2-9.1.198.jar](https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/4300616)

**Comment by Krutoy242** [comment]
`Craft.zs` is script for MC `1.12.2`. Its stated in [Readme](https://github.com/Krutoy242/Craft.zs#installation).

I dont know ZenScript for other versions, so cant help with that.

**Comment by Oskal79** [comment]
Ok, I'm sorry I didn't read the Readme in full, I only studied how the script works, it's a pity that I'm not so attentive :(
