### ISSUE TITLE
support botania mod

### ISSUE THREAD

**Issue by dawsontech30000** [Krutoy242/Craft.zs#5]
not really issues 

https://botaniamod.net/index.html

is anyway you can support rutic altr with your crafttweaks you made?

**Comment by Krutoy242** [comment]
Runic Altair is tweakable with CraftTweaker, yes.

**Comment by dawsontech30000** [comment]
am i allowed to use this  in my own pack 
"A [ZenScript](https://docs.blamejared.com/) auxiliary scripts for quick recipe making."

**Comment by Krutoy242** [comment]
Yes, you are allowed.

**Comment by dawsontech30000** [comment]
Question: What do I need, mod-wise, to get craft.zs to work and load  when installing mods? I'm encountering a lot of errors with mod support. Could you provide a small guide detailing what people need to download and which files they need? I think I may have done something wrong, which is why I'm getting errors.

**Comment by dawsontech30000** [comment]
if just install craft.zs
![image](https://github.com/Krutoy242/Craft.zs/assets/46389381/07d50a57-48a0-44b8-a947-0e330efc2b3f)

**Comment by dawsontech30000** [comment]
might be dumb just confused what i need 

saw whole repo 

this what errors i get

**Comment by dawsontech30000** [comment]
[crafttweaker.log](https://github.com/Krutoy242/Craft.zs/files/14670887/crafttweaker.log)

**Comment by Krutoy242** [comment]
> might be dumb just confused what i need
> 
> saw whole repo
> 
> this what errors i get

How this related to issue topic "Support botania mod"?

I will take a look at logs later, but this is inappropriate place for support.

**Comment by Krutoy242** [comment]
> [crafttweaker.log](https://github.com/Krutoy242/Craft.zs/files/14670887/crafttweaker.log)

Its seems like you installed craft.zs wrongly. Check [installation guide](https://github.com/Krutoy242/Craft.zs#installation) again. You need to put scripts into `scripts/craft/` folder, not in `scripts/`.

**Comment by dawsontech30000** [comment]
can close this all working thanks you
